sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product testn-043
env:
  global:
    -
    # LTD_AWS_ID
      secure: EeNqnxHMHpDdSszHt3yd0pRYzPzig5AowZG3crTqi78/+WMp2mc111DNEWBSsAK1Z8+y25NI1ApkciKwryGUIbqo6nVlbe3C4ertDaaaM2Ddk/dzhcKjjiki3J75k01jwwt/n5QJOHedtWQUypGscjY0NHSYBCo1QQFnCSOhHeKkJ2y5QvvNnWC3hWi9FT6hkpgdJ5MH2xMfOI2+obZgGq5kVuMSGtocI66+BX75DWDiikruE0aYI8XJoICBK17OItCFz2O75IpJt7QaOdeSwtaxxlWpZvatX4jkGRN5cnxJp52Rttf0JGCNtwffD7pGxn52HaoGJvWHVGg1ud+RarVlqb/GexADS/h9xkL8AFEhPQM1BglbtEE+OwOnoKYsz1ELXKomSdcedqcaTOa3COUPfo6Haz8AhUqSqyfbiOFPE3RRdm9sJwZQo6de7k1bE10gZBYKUGuTMvNEWqlPI4yOh77MUCEfngEukLOOJUeIhoH0yAGXKAxVNjEoUJq0UlapZNX0iReMuLG3WXgp4lIFJOtM9hmTjZNUYQbnt3JE3IOqd9Rb3K1ZR/6pm90bLpc60ZAgWfBenTF9XL1NdNEnAXramakPMQl1TlXUjPPCXjKR5j1zXnEkro5Vlek2R+qZN7vM6VG0Me1qtKYjiqTkUpMe/pMxHKyDLdjq7GQ=
    -
    # LTD_AWS_SECRET
      secure: se4FTk+5yF28fGvZfd4zcW9439Bgj8Hgx5fiIYU4PNq977yiTsgsnb3LwZk5nmbTKy8O2JUGwAZhFzmQC8CrHcfuoeTsKVbNRXExosoCOE+EGpQG9o9cuqbrifrdXUqyAKv4tV525l3PjUS5JLiqUdHvk5YtXKIuW9asheEvtlUvBQ9V7WRXfh4uJR2jJEvxAbTnumREVWV8VcZL0Dp5yYXyOe9tEKApLuluk2Vk7NlQx8mw6SFsWZmlyHWHYsZbDYb8tvFUzmkGNggK/dCGrsIxEj4Bajem8k9WZm6jjIGwaYQoC8J2n0Eszk/NvUn9nhGUTUR4+agvgwx24bHi8MdcyYoK8EsQOe4udZ1pkXwCMdr5sWmhOQIW3KSe1L9HtLU06NkQaaTpTpJ5GAgNtUCfxaV5UDRnBwsyeARhEw9GHW0OuwyFk9WLLixbNDzTPbh0Pa7xheykaDiSKDspYOA+oTjLR5bJCWWZuNwojw05z6tYgWBCnp+bwC1TvPv3uS8yZPDTeuhWHdiD3Z7UmkjGR3F/G79mayN88KyPfYVlyFaoO668ij0BKSPqxgCLiEMcgUtvoQUE5Ll05+ff5psSuD8eV88LEjpPh4NxJFE0MSEyAWpDmc9snGANUnvTSlPljOIZGPwp/CV9taPLQyYUrcZ/xL+5lrqnjKqyvFk=
    -
    # LTD_USERNAME
      secure: u+SDq+ph9Y+TKCUdcrr8PSuPoeLLslkIJ7knnywdost2GHz5RN7iGPs8pXjkWW7Xdb5z652WWJ31fK8i/isCYrgVIZVaMjK3RSXpZgRm2Sx0Rac4KiP6bcwvx5CFpc1ERvooJ9m3ovJWKNcQBK9mXClb1tIJT/ClNEoom9Mup8NJvJ6B0XXL5mVs8GXBB0jiFM84j/FWgxN5iKt4bvYTRpd4dQP4TBasfxe+C52JlN6aB4lJxeW9yJk4X/OSLK0Ph1UaHJi5cPvPuy1JnYPTOYgAOBKdZM52PBFxIhbltctqQUAhnascL9Wv3J69lC09Ci4S/B44vODXKf1Ju/Rt1eg3aYfS/OLBfoQxfiTvHyQL8dlEwW/3Ll4rq26/SKyAkHzZvqIUTLylVBdRSzhTHzrylSrLEbUp1rA8zKzdfezlMa2D/qfbEMNt5fePaC41UzdjgHJDkLHmVTbE9p6AFetEr2xRu60yE/bBEACcohHYQNl+0CmRECMrPCbpD/aTLfpMF1s2f1GTcrI/h4xdL6UA9h6G0M/ZP7XwQX5zyXXCmU04KL8SH9JPM8hk1A4xgOyNnDLMlq2TGcSq3opLXZL50GoZInl6jwHLB8TYN2d9Tmnv9httQ7e8atrQAz9dyb7SAJS+vwqeRrImuiFmszctRbX9olIEm+c73k6IA7Y=
    -
    # LTD_PASSWORD
      secure: ly6Fi3AN0D+5KGqujazuEwjeokM8v3Unzhv/RCq8tNm5kOP9bXIt3bl7UkW5K2bXNu94NuAi7F9/PDb7q8IV+LwJWjV7OOiY3z3R7ZwKtgceL8tC5GcewubIW2yvxoPGzTp7xG+9r5qYW3geWdABwgFx0M3tHtwiILuhG5rfxjo+M86Qv+mILttni7Z7azhnJuqwMfsHBUIakr/yUqBBhmNDsXdKxbwBpp8ObkFoBe0oC9i9J33Tl4y2NKGewhp4wlXkZ0OKxqlKgLj+lQCCb4Lye7mdmjwIkw716OdVflhdMxMwUHCOXibtT7yqNRVUCFHeRvHSpxeSZvWNkzPSh17P59YlPztNMhxmcGuIB4PoVBgdoSHA1+2N6TH5XT0PyWEi3ZwvKDIWGCZBUzlBa4NgG15tgggmzdu0YH2pD/xeqcAlnp8hwIXEP5CwfCl63hmCgRUbIzQ6PqeyMzHlyCXNx2EClg7ESy9ZmPjFPmUj/wmZO0rtCmul6ArJALTwQqWBNOHR+2y4p0OK0grVx9FyzItsKKoWX6Ql+tFGeOywzNHgmgVGFD9LiAZwJCwoee718+wU/GRE4+2yji5oGL87KxTN7jAebvS1eRRJfiFJkZzKfOwCxmfDmF5YD1abXr0upQVUHU7HCNJF3JR8EJwiW1pzazxhJgWlVgOvM0U=
